server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WebProject
    username: realestate_user
    password: cosmos12345
    driver-class-name: org.postgresql.Driver



  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update



